# Google Colab Setup

In [1]:
from google.colab import files
uploaded = files.upload()

Saving dataset.json to dataset.json


In [2]:
import json
for key in uploaded.keys():
  raw_data = json.loads(uploaded[key])['data']

In [3]:
!git clone https://github.com/haidarihza/sistem-penilaian-kompetensi-v2

!pip install batchbald_redux

import sys
sys.path.append('/content/sistem-penilaian-kompetensi-v2/Penilaian Kompetensi Inggris')

Cloning into 'sistem-penilaian-kompetensi-v2'...
remote: Enumerating objects: 19311, done.
remote: Counting objects: 100% (1183/1183), done.
remote: Compressing objects: 100% (424/424), done.
remote: Total 19311 (delta 741), reused 1169 (delta 727), pack-reused 18128
Receiving objects: 100% (19311/19311), 163.83 MiB | 14.59 MiB/s, done.
Resolving deltas: 100% (2538/2538), done.
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-

# Evaluation Setup

In [4]:
from src.model import *
import torch

In [5]:
device = torch.device('cuda')

# Active Learning Evaluation

Data split: 7 pool sets / 2 eval sets (1 set = 4 data points)<br>
Base model: sentence-transformers/all-mpnet-base-v2<br>

Acquisition function: PowerBALD (α=5)<br>
Acquisition size: 5<br>
Bayesian sample size: 5<br>
Acquisition step: 4<br>

In [121]:
pool_data = raw_data[:7]
eval_data = raw_data[7:]

transcripts = [transcript for d in pool_data for transcript in d['transcripts']]
competence_sets = [d['competence_levels'] for d in pool_data for _ in range(len(d['transcripts']))]
labels = [label for d in pool_data for label in d['labels']]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

transcripts = [transcript for d in eval_data for transcript in d['transcripts']]
competence_sets = [d['competence_levels'] for d in eval_data for _ in range(len(d['transcripts']))]
labels = [label for d in eval_data for label in d['labels']]
eval_dataset = TCDataset(transcripts, competence_sets, labels)

In [122]:
model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)

In [123]:
# Model prediction on eval dataset (initial)
model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[0.2627, 0.1829, 0.1910, 0.3634],
        [0.2645, 0.2284, 0.2038, 0.3033],
        [0.1308, 0.1516, 0.2125, 0.5051],
        [0.1232, 0.1987, 0.2204, 0.4577],
        [0.2134, 0.2728, 0.2259, 0.2878],
        [0.1900, 0.3128, 0.2226, 0.2746],
        [0.1912, 0.2685, 0.2554, 0.2849],
        [0.2083, 0.2866, 0.2056, 0.2995]], device='cuda:0')
Accuracy: 0.38


## Acquisition Step 1

In [124]:
bayesian_model = BayesianCompetenceModel(model)

In [125]:
bayesian_model.eval()

with torch.no_grad():
    # Split to minimize GPU RAM usage
    scores = []
    n, s = len(pool_dataset), 5
    for i in range(0, n, s):
      score = bayesian_model(pool_dataset.transcripts[i:min(i+s, n)], pool_dataset.competence_sets[i:min(i+s, n)], k=5, tokenizer_padding='max_length')
      scores.append(score)

    scores = torch.cat(scores)
    log_scores = torch.log(scores)
    batch = get_powerbald_batch(log_scores, batch_size=5, alpha=5)

Entropy:   0%|          | 0/28 [00:00<?, ?it/s]

Conditional Entropy:   0%|          | 0/28 [00:00<?, ?it/s]

In [126]:
train_dataset = torch.utils.data.Subset(pool_dataset, batch.indices)

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [127]:
# Model training on 5 epochs

model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.4623 | Train Acc = 0.0000 | Val Loss = 1.2974 | Val Acc = 0.3750
Epoch 2 | Train Loss = 1.3232 | Train Acc = 0.2000 | Val Loss = 1.2938 | Val Acc = 0.3750
Epoch 3 | Train Loss = 1.2379 | Train Acc = 0.2000 | Val Loss = 1.2880 | Val Acc = 0.3750
Epoch 4 | Train Loss = 1.1608 | Train Acc = 0.6000 | Val Loss = 1.2805 | Val Acc = 0.3750
Epoch 5 | Train Loss = 1.0556 | Train Acc = 0.6000 | Val Loss = 1.2704 | Val Acc = 0.3750


In [128]:
# Model prediction on eval dataset
model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[0.2858, 0.2080, 0.1801, 0.3261],
        [0.2504, 0.2484, 0.2124, 0.2888],
        [0.0837, 0.1923, 0.2197, 0.5042],
        [0.1131, 0.2093, 0.2240, 0.4535],
        [0.2086, 0.2831, 0.2275, 0.2808],
        [0.1646, 0.3299, 0.2209, 0.2847],
        [0.1797, 0.2768, 0.2557, 0.2878],
        [0.1920, 0.2936, 0.2046, 0.3098]], device='cuda:0')
Accuracy: 0.38


## Acquisition Step 2

In [129]:
bayesian_model = BayesianCompetenceModel(model)

In [130]:
bayesian_model.eval()
with torch.no_grad():
    # Split to minimize GPU RAM usage
    scores = []
    n, s = len(pool_dataset), 5
    for i in range(0, n, s):
      score = bayesian_model(pool_dataset.transcripts[i:min(i+s, n)], pool_dataset.competence_sets[i:min(i+s, n)], k=5, tokenizer_padding='max_length')
      scores.append(score)

    scores = torch.cat(scores)
    log_scores = torch.log(scores)
    batch = get_powerbald_batch(log_scores, batch_size=5, alpha=5)

Entropy:   0%|          | 0/23 [00:00<?, ?it/s]

Conditional Entropy:   0%|          | 0/23 [00:00<?, ?it/s]

In [131]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [132]:
# Model training on 5 epochs

model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.4053 | Train Acc = 0.3000 | Val Loss = 1.2945 | Val Acc = 0.3750
Epoch 2 | Train Loss = 1.2983 | Train Acc = 0.4000 | Val Loss = 1.2821 | Val Acc = 0.3750
Epoch 3 | Train Loss = 1.2288 | Train Acc = 0.5000 | Val Loss = 1.2645 | Val Acc = 0.3750
Epoch 4 | Train Loss = 1.0564 | Train Acc = 0.6000 | Val Loss = 1.2388 | Val Acc = 0.3750
Epoch 5 | Train Loss = 0.8353 | Train Acc = 0.6000 | Val Loss = 1.2318 | Val Acc = 0.5000


In [133]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[3.4570e-01, 2.0368e-01, 1.2323e-01, 3.2738e-01],
        [2.8193e-01, 2.4957e-01, 1.8040e-01, 2.8810e-01],
        [4.6008e-20, 8.2498e-02, 1.3670e-01, 7.8080e-01],
        [1.5986e-20, 2.0150e-01, 1.9150e-01, 6.0700e-01],
        [2.6475e-01, 2.7360e-01, 2.1076e-01, 2.5090e-01],
        [1.9192e-01, 3.4488e-01, 2.0910e-01, 2.5409e-01],
        [2.0569e-01, 2.5990e-01, 2.6270e-01, 2.7171e-01],
        [2.2425e-01, 2.8648e-01, 1.8342e-01, 3.0585e-01]], device='cuda:0')
Accuracy: 0.50


## Acquisition Step 3

In [134]:
bayesian_model = BayesianCompetenceModel(model)

In [135]:
bayesian_model.eval()

with torch.no_grad():
    # Split to minimize GPU RAM usage
    scores = []
    n, s = len(pool_dataset), 5
    for i in range(0, n, s):
      score = bayesian_model(pool_dataset.transcripts[i:min(i+s, n)], pool_dataset.competence_sets[i:min(i+s, n)], k=5, tokenizer_padding='max_length')
      scores.append(score)

    scores = torch.cat(scores)
    log_scores = torch.log(scores)
    batch = get_powerbald_batch(log_scores, batch_size=5, alpha=5)

Entropy:   0%|          | 0/18 [00:00<?, ?it/s]

Conditional Entropy:   0%|          | 0/18 [00:00<?, ?it/s]

In [136]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [137]:
# Model training on 5 epochs

model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.4055 | Train Acc = 0.2000 | Val Loss = 1.2934 | Val Acc = 0.3750
Epoch 2 | Train Loss = 1.3311 | Train Acc = 0.5333 | Val Loss = 1.2825 | Val Acc = 0.3750
Epoch 3 | Train Loss = 1.2337 | Train Acc = 0.5333 | Val Loss = 1.2552 | Val Acc = 0.3750
Epoch 4 | Train Loss = 1.1314 | Train Acc = 0.7333 | Val Loss = 1.2125 | Val Acc = 0.5000
Epoch 5 | Train Loss = 0.7766 | Train Acc = 0.8000 | Val Loss = 6.3079 | Val Acc = 0.6250


In [138]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[6.8100e-01, 7.6322e-02, 5.9796e-20, 2.4268e-01],
        [3.8150e-01, 2.3405e-01, 1.4343e-01, 2.4101e-01],
        [1.0497e-19, 1.0497e-19, 1.0497e-19, 1.0000e+00],
        [2.3902e-20, 1.1759e-01, 1.2506e-01, 7.5734e-01],
        [2.9453e-01, 2.8566e-01, 1.6161e-01, 2.5819e-01],
        [1.3686e-01, 4.2453e-01, 1.0787e-01, 3.3074e-01],
        [1.7441e-01, 2.7126e-01, 2.2971e-01, 3.2462e-01],
        [2.2436e-01, 2.9683e-01, 1.4537e-01, 3.3344e-01]], device='cuda:0')
Accuracy: 0.62


## Acquisition Step 4

In [139]:
bayesian_model = BayesianCompetenceModel(model)

In [140]:
bayesian_model.eval()

with torch.no_grad():
    # Split to minimize GPU RAM usage
    scores = []
    n, s = len(pool_dataset), 5
    for i in range(0, n, s):
      score = bayesian_model(pool_dataset.transcripts[i:min(i+s, n)], pool_dataset.competence_sets[i:min(i+s, n)], k=5, tokenizer_padding='max_length')
      scores.append(score)

    scores = torch.cat(scores)
    log_scores = torch.log(scores)
    batch = get_powerbald_batch(log_scores, batch_size=5, alpha=5)

Entropy:   0%|          | 0/13 [00:00<?, ?it/s]

Conditional Entropy:   0%|          | 0/13 [00:00<?, ?it/s]

In [141]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [142]:
# Model training on 5 epochs

model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.3840 | Train Acc = 0.2500 | Val Loss = 1.3056 | Val Acc = 0.3750
Epoch 2 | Train Loss = 1.3190 | Train Acc = 0.4500 | Val Loss = 1.2880 | Val Acc = 0.3750
Epoch 3 | Train Loss = 1.2444 | Train Acc = 0.6000 | Val Loss = 1.2565 | Val Acc = 0.3750
Epoch 4 | Train Loss = 1.0087 | Train Acc = 0.5000 | Val Loss = 6.4003 | Val Acc = 0.5000
Epoch 5 | Train Loss = 0.6443 | Train Acc = 0.7000 | Val Loss = 6.7099 | Val Acc = 0.6250


In [143]:
# Model prediction on eval dataset after training
model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[2.5000e-01, 2.5000e-01, 2.5000e-01, 2.5000e-01],
        [9.9600e-01, 4.0040e-03, 1.4975e-19, 1.4975e-19],
        [3.4652e-19, 3.4652e-19, 3.4652e-19, 1.0000e+00],
        [4.2819e-20, 4.2819e-20, 4.2819e-20, 1.0000e+00],
        [3.9298e-01, 2.6579e-01, 9.4700e-04, 3.4028e-01],
        [3.8493e-20, 5.3912e-01, 3.8493e-20, 4.6088e-01],
        [1.3484e-01, 2.7922e-01, 1.7207e-01, 4.1387e-01],
        [2.2429e-01, 2.9977e-01, 9.0678e-02, 3.8526e-01]], device='cuda:0')
Accuracy: 0.62
