# Google Colab Setup

In [1]:
from google.colab import files
uploaded = files.upload()

Saving dataset.json to dataset.json


In [2]:
import json
for key in uploaded.keys():
  raw_data = json.loads(uploaded[key])['data']

In [3]:
!git clone https://github.com/haidarihza/sistem-penilaian-kompetensi-v2

!pip install batchbald_redux

import sys
sys.path.append('/content/sistem-penilaian-kompetensi-v2/Penilaian Kompetensi Inggris')

Cloning into 'sistem-penilaian-kompetensi-v2'...
remote: Enumerating objects: 19311, done.
remote: Counting objects: 100% (1183/1183), done.
remote: Compressing objects: 100% (424/424), done.
remote: Total 19311 (delta 741), reused 1169 (delta 727), pack-reused 18128
Receiving objects: 100% (19311/19311), 163.83 MiB | 16.30 MiB/s, done.
Resolving deltas: 100% (2538/2538), done.
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-

# Evaluation Setup

In [4]:
from src.model import *
import torch

In [5]:
device = torch.device('cuda')

# Active Learning Evaluation

Data split: 7 pool sets / 2 eval sets (1 set = 4 data points)<br>
Base model: sentence-transformers/all-mpnet-base-v2<br>

Acquisition function: Random<br>
Acquisition size: 5<br>
Acquisition step: 4<br>

In [101]:
pool_data = raw_data[:7]
eval_data = raw_data[7:]

transcripts = [transcript for d in pool_data for transcript in d['transcripts']]
competence_sets = [d['competence_levels'] for d in pool_data for _ in range(len(d['transcripts']))]
labels = [label for d in pool_data for label in d['labels']]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

transcripts = [transcript for d in eval_data for transcript in d['transcripts']]
competence_sets = [d['competence_levels'] for d in eval_data for _ in range(len(d['transcripts']))]
labels = [label for d in eval_data for label in d['labels']]
eval_dataset = TCDataset(transcripts, competence_sets, labels)

In [102]:
model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)

In [103]:
# Model prediction on eval dataset (initial)

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[0.2627, 0.1829, 0.1910, 0.3634],
        [0.2645, 0.2284, 0.2038, 0.3033],
        [0.1308, 0.1516, 0.2125, 0.5051],
        [0.1232, 0.1987, 0.2204, 0.4577],
        [0.2134, 0.2728, 0.2259, 0.2878],
        [0.1900, 0.3128, 0.2226, 0.2746],
        [0.1912, 0.2685, 0.2554, 0.2849],
        [0.2083, 0.2866, 0.2056, 0.2995]], device='cuda:0')
Accuracy: 0.38


## Acquisition Step 1

In [104]:
batch = get_random_batch(len(pool_dataset), batch_size=5)

In [105]:
train_dataset = torch.utils.data.Subset(pool_dataset, batch.indices)

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [106]:
# Model training on 5 epochs

model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.4059 | Train Acc = 0.2000 | Val Loss = 1.3022 | Val Acc = 0.3750
Epoch 2 | Train Loss = 1.2784 | Train Acc = 0.4000 | Val Loss = 1.2978 | Val Acc = 0.3750
Epoch 3 | Train Loss = 1.2002 | Train Acc = 0.4000 | Val Loss = 1.2890 | Val Acc = 0.3750
Epoch 4 | Train Loss = 1.0848 | Train Acc = 0.8000 | Val Loss = 1.2785 | Val Acc = 0.3750
Epoch 5 | Train Loss = 0.9098 | Train Acc = 0.8000 | Val Loss = 1.2692 | Val Acc = 0.3750


In [107]:
# Model prediction on eval dataset

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[3.0647e-01, 1.1324e-01, 1.7892e-01, 4.0137e-01],
        [2.7650e-01, 2.0622e-01, 2.1296e-01, 3.0432e-01],
        [3.5400e-20, 3.2727e-02, 2.0667e-01, 7.6061e-01],
        [6.5458e-02, 1.6663e-01, 2.2101e-01, 5.4690e-01],
        [1.7226e-01, 3.1129e-01, 2.0359e-01, 3.1286e-01],
        [1.1004e-01, 3.9355e-01, 1.7334e-01, 3.2307e-01],
        [1.3683e-01, 2.9535e-01, 2.3634e-01, 3.3148e-01],
        [1.7267e-01, 3.1394e-01, 1.7331e-01, 3.4007e-01]], device='cuda:0')
Accuracy: 0.38


## Acquisition Step 2

In [108]:
batch = get_random_batch(len(pool_dataset), batch_size=5)

In [109]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [110]:
# Model training on 5 epochs

model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.3529 | Train Acc = 0.4000 | Val Loss = 1.2916 | Val Acc = 0.3750
Epoch 2 | Train Loss = 1.2504 | Train Acc = 0.7000 | Val Loss = 1.2809 | Val Acc = 0.3750
Epoch 3 | Train Loss = 1.1725 | Train Acc = 0.7000 | Val Loss = 1.2629 | Val Acc = 0.3750
Epoch 4 | Train Loss = 0.9516 | Train Acc = 0.9000 | Val Loss = 1.2412 | Val Acc = 0.5000
Epoch 5 | Train Loss = 0.7294 | Train Acc = 0.8000 | Val Loss = 1.2423 | Val Acc = 0.5000


In [111]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[4.5883e-01, 1.0639e-01, 1.0950e-01, 3.2528e-01],
        [3.4531e-01, 2.0166e-01, 1.8701e-01, 2.6602e-01],
        [5.4778e-20, 5.4778e-20, 1.0340e-01, 8.9660e-01],
        [1.5042e-03, 1.8073e-01, 2.0259e-01, 6.1518e-01],
        [2.4620e-01, 2.8906e-01, 1.8669e-01, 2.7804e-01],
        [1.3929e-01, 3.9451e-01, 1.3518e-01, 3.3102e-01],
        [1.7377e-01, 2.6583e-01, 2.5146e-01, 3.0894e-01],
        [2.0310e-01, 2.9842e-01, 1.6265e-01, 3.3584e-01]], device='cuda:0')
Accuracy: 0.50


## Acquisition Step 3

In [112]:
batch = get_random_batch(len(pool_dataset), batch_size=5)

In [113]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [114]:
# Model training on 5 epochs

model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.3276 | Train Acc = 0.4000 | Val Loss = 1.2871 | Val Acc = 0.3750
Epoch 2 | Train Loss = 1.2480 | Train Acc = 0.5333 | Val Loss = 1.2645 | Val Acc = 0.3750
Epoch 3 | Train Loss = 1.0731 | Train Acc = 0.6667 | Val Loss = 1.2531 | Val Acc = 0.3750
Epoch 4 | Train Loss = 0.8181 | Train Acc = 0.7333 | Val Loss = 6.4466 | Val Acc = 0.3750
Epoch 5 | Train Loss = 0.6192 | Train Acc = 0.6667 | Val Loss = 6.2985 | Val Acc = 0.5000


In [115]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[5.3460e-01, 1.0164e-19, 1.0164e-19, 4.6540e-01],
        [3.6607e-01, 1.9287e-01, 6.5417e-02, 3.7564e-01],
        [9.0030e-20, 9.0030e-20, 9.0030e-20, 1.0000e+00],
        [2.9324e-20, 2.9324e-20, 2.9324e-20, 1.0000e+00],
        [2.7619e-01, 2.8805e-01, 1.9769e-01, 2.3807e-01],
        [3.8495e-02, 4.5222e-01, 1.5943e-01, 3.4985e-01],
        [7.9542e-02, 2.3768e-01, 2.9228e-01, 3.9049e-01],
        [1.8029e-01, 2.9620e-01, 1.3750e-01, 3.8602e-01]], device='cuda:0')
Accuracy: 0.50


## Acquisition Step 4

In [116]:
batch = get_random_batch(len(pool_dataset), batch_size=5)

In [117]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [118]:
# Model training on 5 epochs

model = CompetenceModel.load('sentence-transformers/all-mpnet-base-v2', 'biencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.3627 | Train Acc = 0.3000 | Val Loss = 1.2859 | Val Acc = 0.3750
Epoch 2 | Train Loss = 1.2373 | Train Acc = 0.5000 | Val Loss = 1.2560 | Val Acc = 0.3750
Epoch 3 | Train Loss = 1.0378 | Train Acc = 0.5500 | Val Loss = 6.4484 | Val Acc = 0.5000
Epoch 4 | Train Loss = 2.8638 | Train Acc = 0.6000 | Val Loss = 6.2015 | Val Acc = 0.5000
Epoch 5 | Train Loss = 0.6142 | Train Acc = 0.6500 | Val Loss = 6.1235 | Val Acc = 0.5000


In [119]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[7.8368e-01, 7.7504e-20, 7.7504e-20, 2.1632e-01],
        [3.9787e-01, 2.4866e-01, 1.5102e-01, 2.0245e-01],
        [1.8975e-19, 1.8975e-19, 1.8975e-19, 1.0000e+00],
        [3.7710e-20, 3.7710e-20, 3.7710e-20, 1.0000e+00],
        [3.0324e-01, 3.3201e-01, 1.1692e-01, 2.4783e-01],
        [3.3673e-20, 6.1323e-01, 3.3673e-20, 3.8677e-01],
        [1.1353e-01, 3.1652e-01, 2.1434e-01, 3.5561e-01],
        [1.9824e-01, 3.3181e-01, 1.1000e-01, 3.5995e-01]], device='cuda:0')
Accuracy: 0.50
