# Google Colab Setup

In [1]:
from google.colab import files
uploaded = files.upload()

Saving dataset.json to dataset.json


In [2]:
import json
for key in uploaded.keys():
  raw_data = json.loads(uploaded[key])['data']

In [3]:
!git clone https://github.com/haidarihza/sistem-penilaian-kompetensi-v2

!pip install batchbald_redux

import sys
sys.path.append('/content/sistem-penilaian-kompetensi-v2/Penilaian Kompetensi Inggris')

Cloning into 'sistem-penilaian-kompetensi-v2'...
remote: Enumerating objects: 19311, done.
remote: Counting objects: 100% (1183/1183), done.
remote: Compressing objects: 100% (424/424), done.
remote: Total 19311 (delta 741), reused 1169 (delta 727), pack-reused 18128
Receiving objects: 100% (19311/19311), 163.83 MiB | 15.57 MiB/s, done.
Resolving deltas: 100% (2538/2538), done.
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-

# Evaluation Setup

In [4]:
from src.model import *
import torch

In [5]:
device = torch.device('cuda')

# Active Learning Evaluation

Data split: 7 pool sets / 2 eval sets (1 set = 4 data points)<br>
Base model: cross-encoder/nli-deberta-v3-base<br>

Acquisition function: PowerBALD (α=5)<br>
Acquisition size: 5<br>
Bayesian sample size: 5<br>
Acquisition step: 4<br>

In [129]:
pool_data = raw_data[:7]
eval_data = raw_data[7:]

transcripts = [transcript for d in pool_data for transcript in d['transcripts']]
competence_sets = [d['competence_levels'] for d in pool_data for _ in range(len(d['transcripts']))]
labels = [label for d in pool_data for label in d['labels']]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

transcripts = [transcript for d in eval_data for transcript in d['transcripts']]
competence_sets = [d['competence_levels'] for d in eval_data for _ in range(len(d['transcripts']))]
labels = [label for d in eval_data for label in d['labels']]
eval_dataset = TCDataset(transcripts, competence_sets, labels)

In [130]:
model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)

In [132]:
# Model prediction on eval dataset (initial)

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[8.8539e-01, 2.4814e-03, 2.4600e-03, 1.0966e-01],
        [3.1869e-01, 5.6854e-02, 2.3564e-01, 3.8882e-01],
        [9.1472e-02, 7.9833e-02, 2.5287e-01, 5.7583e-01],
        [1.7241e-03, 1.1876e-03, 1.6624e-03, 9.9543e-01],
        [7.4673e-01, 2.5297e-01, 1.4159e-04, 1.6520e-04],
        [3.3627e-03, 9.5070e-01, 4.5272e-02, 6.6608e-04],
        [5.4032e-02, 1.3424e-01, 8.0497e-01, 6.7584e-03],
        [1.4482e-01, 7.0768e-01, 9.1833e-02, 5.5661e-02]], device='cuda:0')
Accuracy: 0.62


## Acquisition Step 1

In [133]:
bayesian_model = BayesianCompetenceModel(model)

In [134]:
bayesian_model.eval()

with torch.no_grad():
    # Split to minimize GPU RAM usage
    scores = []
    n, s = len(pool_dataset), 5
    for i in range(0, n, s):
      score = bayesian_model(pool_dataset.transcripts[i:min(i+s, n)], pool_dataset.competence_sets[i:min(i+s, n)], k=5, tokenizer_padding='max_length')
      scores.append(score)

    scores = torch.cat(scores)
    log_scores = torch.log(scores)
    batch = get_powerbald_batch(log_scores, batch_size=5, alpha=5)

Entropy:   0%|          | 0/28 [00:00<?, ?it/s]

Conditional Entropy:   0%|          | 0/28 [00:00<?, ?it/s]

In [135]:
train_dataset = torch.utils.data.Subset(pool_dataset, batch.indices)

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [136]:
# Model training on 5 epochs

model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 3.0631 | Train Acc = 0.4000 | Val Loss = 1.7883 | Val Acc = 0.6250
Epoch 2 | Train Loss = 2.3281 | Train Acc = 0.4000 | Val Loss = 2.0076 | Val Acc = 0.6250
Epoch 3 | Train Loss = 1.4579 | Train Acc = 0.6000 | Val Loss = 1.9120 | Val Acc = 0.3750
Epoch 4 | Train Loss = 1.0734 | Train Acc = 0.4000 | Val Loss = 1.8811 | Val Acc = 0.5000
Epoch 5 | Train Loss = 1.0653 | Train Acc = 0.6000 | Val Loss = 1.8724 | Val Acc = 0.6250


In [137]:
# Model prediction on eval dataset

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[0.4635, 0.0430, 0.0311, 0.4624],
        [0.3049, 0.0075, 0.3022, 0.3855],
        [0.0035, 0.0012, 0.4928, 0.5025],
        [0.0087, 0.0019, 0.0442, 0.9451],
        [0.4931, 0.4921, 0.0130, 0.0018],
        [0.3295, 0.3316, 0.3309, 0.0080],
        [0.3271, 0.3282, 0.3296, 0.0150],
        [0.0945, 0.4849, 0.4171, 0.0036]], device='cuda:0')
Accuracy: 0.62


## Acquisition Step 2

In [138]:
bayesian_model = BayesianCompetenceModel(model)

In [139]:
bayesian_model.eval()

with torch.no_grad():
    # Split to minimize GPU RAM usage
    scores = []
    n, s = len(pool_dataset), 5
    for i in range(0, n, s):
      score = bayesian_model(pool_dataset.transcripts[i:min(i+s, n)], pool_dataset.competence_sets[i:min(i+s, n)], k=5, tokenizer_padding='max_length')
      scores.append(score)

    scores = torch.cat(scores)
    log_scores = torch.log(scores)
    batch = get_powerbald_batch(log_scores, batch_size=5, alpha=5)

Entropy:   0%|          | 0/23 [00:00<?, ?it/s]

Conditional Entropy:   0%|          | 0/23 [00:00<?, ?it/s]

In [140]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [141]:
# Model training on 5 epochs

model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.3720 | Train Acc = 0.5000 | Val Loss = 1.2211 | Val Acc = 0.5000
Epoch 2 | Train Loss = 0.8253 | Train Acc = 0.7000 | Val Loss = 1.1214 | Val Acc = 0.5000
Epoch 3 | Train Loss = 0.6412 | Train Acc = 0.8000 | Val Loss = 1.1833 | Val Acc = 0.5000
Epoch 4 | Train Loss = 0.7804 | Train Acc = 0.6000 | Val Loss = 1.3830 | Val Acc = 0.3750
Epoch 5 | Train Loss = 0.2555 | Train Acc = 0.9000 | Val Loss = 1.6217 | Val Acc = 0.5000


In [142]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[3.4649e-01, 1.9740e-02, 1.4186e-02, 6.1959e-01],
        [3.1052e-01, 1.1395e-01, 1.9222e-01, 3.8331e-01],
        [3.8478e-02, 3.5315e-02, 5.3211e-01, 3.9410e-01],
        [3.2008e-03, 2.4833e-03, 4.6235e-03, 9.8969e-01],
        [5.0760e-01, 4.9207e-01, 1.7288e-04, 1.5474e-04],
        [1.0744e-01, 8.8811e-01, 3.6672e-03, 7.8224e-04],
        [8.7032e-02, 8.5368e-01, 4.8796e-02, 1.0494e-02],
        [2.2961e-02, 9.5062e-01, 2.1346e-02, 5.0752e-03]], device='cuda:0')
Accuracy: 0.50


## Acquisition Step 3

In [143]:
bayesian_model = BayesianCompetenceModel(model)

In [144]:
bayesian_model.eval()

with torch.no_grad():
    # Split to minimize GPU RAM usage
    scores = []
    n, s = len(pool_dataset), 5
    for i in range(0, n, s):
      score = bayesian_model(pool_dataset.transcripts[i:min(i+s, n)], pool_dataset.competence_sets[i:min(i+s, n)], k=5, tokenizer_padding='max_length')
      scores.append(score)

    scores = torch.cat(scores)
    log_scores = torch.log(scores)
    batch = get_powerbald_batch(log_scores, batch_size=5, alpha=5)

Entropy:   0%|          | 0/18 [00:00<?, ?it/s]

Conditional Entropy:   0%|          | 0/18 [00:00<?, ?it/s]

In [145]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [146]:
# Model training on 5 epochs

model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 2.2859 | Train Acc = 0.4000 | Val Loss = 0.9570 | Val Acc = 0.5000
Epoch 2 | Train Loss = 1.2913 | Train Acc = 0.4667 | Val Loss = 1.0331 | Val Acc = 0.5000
Epoch 3 | Train Loss = 1.0516 | Train Acc = 0.8000 | Val Loss = 1.0852 | Val Acc = 0.5000
Epoch 4 | Train Loss = 1.1377 | Train Acc = 0.5333 | Val Loss = 1.1135 | Val Acc = 0.5000
Epoch 5 | Train Loss = 1.1947 | Train Acc = 0.4667 | Val Loss = 1.1452 | Val Acc = 0.3750


In [147]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[0.3760, 0.1004, 0.0757, 0.4480],
        [0.3345, 0.1658, 0.2303, 0.2694],
        [0.1573, 0.1523, 0.2740, 0.4163],
        [0.0551, 0.0536, 0.0580, 0.8333],
        [0.7194, 0.1770, 0.0543, 0.0492],
        [0.3461, 0.5169, 0.0819, 0.0551],
        [0.3988, 0.3284, 0.1531, 0.1196],
        [0.3118, 0.3831, 0.1755, 0.1296]], device='cuda:0')
Accuracy: 0.38


## Acquisition Step 4

In [148]:
bayesian_model = BayesianCompetenceModel(model)

In [149]:
bayesian_model.eval()

with torch.no_grad():
    # Split to minimize GPU RAM usage
    scores = []
    n, s = len(pool_dataset), 5
    for i in range(0, n, s):
      score = bayesian_model(pool_dataset.transcripts[i:min(i+s, n)], pool_dataset.competence_sets[i:min(i+s, n)], k=5, tokenizer_padding='max_length')
      scores.append(score)

    scores = torch.cat(scores)
    log_scores = torch.log(scores)
    batch = get_powerbald_batch(log_scores, batch_size=5, alpha=5)

Entropy:   0%|          | 0/13 [00:00<?, ?it/s]

Conditional Entropy:   0%|          | 0/13 [00:00<?, ?it/s]

In [150]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [151]:
# Model training on 5 epochs

model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 2.2275 | Train Acc = 0.3500 | Val Loss = 1.8846 | Val Acc = 0.5000
Epoch 2 | Train Loss = 1.1407 | Train Acc = 0.6000 | Val Loss = 2.1957 | Val Acc = 0.5000
Epoch 3 | Train Loss = 1.2603 | Train Acc = 0.6000 | Val Loss = 2.1600 | Val Acc = 0.5000
Epoch 4 | Train Loss = 1.1678 | Train Acc = 0.6000 | Val Loss = 2.1440 | Val Acc = 0.5000
Epoch 5 | Train Loss = 1.0032 | Train Acc = 0.6000 | Val Loss = 1.8861 | Val Acc = 0.5000


In [152]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[0.4444, 0.0221, 0.1081, 0.4255],
        [0.2349, 0.0178, 0.0383, 0.7091],
        [0.0052, 0.0034, 0.5636, 0.4278],
        [0.0040, 0.0027, 0.0187, 0.9746],
        [0.4990, 0.4955, 0.0022, 0.0033],
        [0.5070, 0.4793, 0.0050, 0.0087],
        [0.2656, 0.6391, 0.0201, 0.0752],
        [0.0287, 0.9058, 0.0521, 0.0134]], device='cuda:0')
Accuracy: 0.50
