# Google Colab Setup

In [1]:
from google.colab import files
uploaded = files.upload()

Saving dataset.json to dataset.json


In [2]:
import json
for key in uploaded.keys():
  raw_data = json.loads(uploaded[key])['data']

In [3]:
!git clone https://github.com/haidarihza/sistem-penilaian-kompetensi-v2

!pip install batchbald_redux

import sys
sys.path.append('/content/sistem-penilaian-kompetensi-v2/Penilaian Kompetensi Inggris')

Cloning into 'sistem-penilaian-kompetensi-v2'...
remote: Enumerating objects: 19311, done.
remote: Counting objects: 100% (1183/1183), done.
remote: Compressing objects: 100% (424/424), done.
remote: Total 19311 (delta 741), reused 1169 (delta 727), pack-reused 18128
Receiving objects: 100% (19311/19311), 163.83 MiB | 20.31 MiB/s, done.
Resolving deltas: 100% (2538/2538), done.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 8.6 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvi

# Evaluation Setup

In [4]:
from src.model import *
import torch

In [5]:
device = torch.device('cuda')

# Active Learning Evaluation

Data split: 7 pool sets / 2 eval sets (1 set = 4 data points)<br>
Base model: cross-encoder/nli-deberta-v3-base<br>

Acquisition function: Random<br>
Acquisition size: 5<br>
Acquisition step: 4<br>

In [101]:
pool_data = raw_data[:7]
eval_data = raw_data[7:]

transcripts = [transcript for d in pool_data for transcript in d['transcripts']]
competence_sets = [d['competence_levels'] for d in pool_data for _ in range(len(d['transcripts']))]
labels = [label for d in pool_data for label in d['labels']]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

transcripts = [transcript for d in eval_data for transcript in d['transcripts']]
competence_sets = [d['competence_levels'] for d in eval_data for _ in range(len(d['transcripts']))]
labels = [label for d in eval_data for label in d['labels']]
eval_dataset = TCDataset(transcripts, competence_sets, labels)

In [102]:
model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)

In [103]:
# Model prediction on eval dataset (initial)

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[8.8539e-01, 2.4814e-03, 2.4600e-03, 1.0966e-01],
        [3.1869e-01, 5.6854e-02, 2.3564e-01, 3.8882e-01],
        [9.1472e-02, 7.9833e-02, 2.5287e-01, 5.7583e-01],
        [1.7241e-03, 1.1876e-03, 1.6624e-03, 9.9543e-01],
        [7.4673e-01, 2.5297e-01, 1.4159e-04, 1.6520e-04],
        [3.3627e-03, 9.5070e-01, 4.5272e-02, 6.6608e-04],
        [5.4032e-02, 1.3424e-01, 8.0497e-01, 6.7584e-03],
        [1.4482e-01, 7.0768e-01, 9.1833e-02, 5.5661e-02]], device='cuda:0')
Accuracy: 0.62


## Acquisition Step 1

In [104]:
batch = get_random_batch(len(pool_dataset), batch_size=5)

In [105]:
train_dataset = torch.utils.data.Subset(pool_dataset, batch.indices)

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [106]:
# Model training on 5 epochs

model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 0.8102 | Train Acc = 0.8000 | Val Loss = 1.1838 | Val Acc = 0.6250
Epoch 2 | Train Loss = 0.3180 | Train Acc = 1.0000 | Val Loss = 0.9033 | Val Acc = 0.6250
Epoch 3 | Train Loss = 0.1954 | Train Acc = 1.0000 | Val Loss = 0.9575 | Val Acc = 0.5000
Epoch 4 | Train Loss = 0.1333 | Train Acc = 1.0000 | Val Loss = 1.0728 | Val Acc = 0.6250
Epoch 5 | Train Loss = 0.0596 | Train Acc = 1.0000 | Val Loss = 1.2916 | Val Acc = 0.6250


In [107]:
# Model prediction on eval dataset

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[5.9526e-01, 1.8548e-03, 1.3560e-03, 4.0153e-01],
        [3.4863e-01, 4.8072e-02, 1.6119e-01, 4.4211e-01],
        [4.9153e-02, 3.1056e-02, 5.8676e-01, 3.3303e-01],
        [1.1103e-03, 6.4446e-04, 1.2307e-03, 9.9701e-01],
        [5.0525e-01, 4.9450e-01, 1.2964e-04, 1.1398e-04],
        [2.0477e-02, 9.6500e-01, 1.3882e-02, 6.3814e-04],
        [1.7623e-01, 5.7619e-01, 2.0388e-01, 4.3700e-02],
        [4.1563e-02, 8.8272e-01, 5.6157e-02, 1.9555e-02]], device='cuda:0')
Accuracy: 0.62


## Acquisition Step 2

In [108]:
batch = get_random_batch(len(pool_dataset), batch_size=5)

In [109]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [110]:
# Model training on 5 epochs

model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.7564 | Train Acc = 0.4000 | Val Loss = 0.8857 | Val Acc = 0.6250
Epoch 2 | Train Loss = 1.1241 | Train Acc = 0.4000 | Val Loss = 0.8742 | Val Acc = 0.6250
Epoch 3 | Train Loss = 0.6447 | Train Acc = 0.7000 | Val Loss = 1.1559 | Val Acc = 0.6250
Epoch 4 | Train Loss = 0.5960 | Train Acc = 0.7000 | Val Loss = 1.3141 | Val Acc = 0.6250
Epoch 5 | Train Loss = 0.3487 | Train Acc = 1.0000 | Val Loss = 1.0872 | Val Acc = 0.6250


In [111]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[9.5082e-01, 1.8541e-03, 1.6815e-03, 4.5647e-02],
        [3.4201e-01, 7.1043e-02, 3.0159e-01, 2.8536e-01],
        [7.1898e-02, 5.5014e-02, 2.7196e-01, 6.0113e-01],
        [2.9826e-03, 1.8693e-03, 3.7652e-03, 9.9138e-01],
        [6.9360e-01, 3.0593e-01, 2.3047e-04, 2.3988e-04],
        [1.7494e-02, 9.5471e-01, 2.6820e-02, 9.7824e-04],
        [2.1963e-01, 2.0386e-01, 5.4971e-01, 2.6807e-02],
        [7.7902e-02, 7.5724e-01, 1.3968e-01, 2.5179e-02]], device='cuda:0')
Accuracy: 0.62


## Acquisition Step 3

In [112]:
batch = get_random_batch(len(pool_dataset), batch_size=5)

In [113]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [114]:
# Model training on 5 epochs

model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 1.5890 | Train Acc = 0.4000 | Val Loss = 0.8660 | Val Acc = 0.6250
Epoch 2 | Train Loss = 0.9683 | Train Acc = 0.6000 | Val Loss = 0.9065 | Val Acc = 0.6250
Epoch 3 | Train Loss = 0.8083 | Train Acc = 0.6000 | Val Loss = 1.7076 | Val Acc = 0.5000
Epoch 4 | Train Loss = 0.9308 | Train Acc = 0.7333 | Val Loss = 1.9469 | Val Acc = 0.6250
Epoch 5 | Train Loss = 0.9022 | Train Acc = 0.6667 | Val Loss = 1.8328 | Val Acc = 0.6250


In [115]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[6.3249e-01, 9.3796e-04, 8.6715e-04, 3.6570e-01],
        [4.4157e-01, 2.9138e-02, 2.2080e-01, 3.0849e-01],
        [1.7792e-02, 7.3247e-03, 6.9816e-01, 2.7672e-01],
        [1.2018e-03, 5.8204e-04, 2.1762e-03, 9.9604e-01],
        [5.0079e-01, 4.9823e-01, 5.2526e-04, 4.5540e-04],
        [4.7833e-01, 4.9750e-01, 2.2433e-02, 1.7397e-03],
        [1.3208e-01, 8.2692e-01, 3.1166e-02, 9.8325e-03],
        [1.6972e-02, 9.2944e-01, 4.9284e-02, 4.3072e-03]], device='cuda:0')
Accuracy: 0.62


## Acquisition Step 4

In [116]:
batch = get_random_batch(len(pool_dataset), batch_size=5)

In [117]:
train_dataset = torch.utils.data.ConcatDataset([train_dataset, torch.utils.data.Subset(pool_dataset, batch.indices)])

transcripts = [t for i, t in enumerate(pool_dataset.transcripts) if i not in batch.indices]
competence_sets = [c for i, c in enumerate(pool_dataset.competence_sets) if i not in batch.indices]
labels = [l for i, l in enumerate(pool_dataset.label_indices) if i not in batch.indices]
pool_dataset = TCDataset(transcripts, competence_sets, labels)

In [118]:
# Model training on 5 epochs

model = CompetenceModel.load('cross-encoder/nli-deberta-v3-base', 'crossencoder', state_dict_path=None, device=device)
model.train()
model.fit(train_dataset, eval_dataset, epochs=5, batch_size=4, early_stop=False,
          optimizer_cls=torch.optim.Adam, optimizer_params={'lr': 1e-5})

Epoch 1 | Train Loss = 2.3410 | Train Acc = 0.4500 | Val Loss = 1.5620 | Val Acc = 0.6250
Epoch 2 | Train Loss = 1.1984 | Train Acc = 0.5500 | Val Loss = 1.7435 | Val Acc = 0.5000
Epoch 3 | Train Loss = 0.8340 | Train Acc = 0.6500 | Val Loss = 1.7100 | Val Acc = 0.5000
Epoch 4 | Train Loss = 0.8092 | Train Acc = 0.6500 | Val Loss = 1.5315 | Val Acc = 0.6250
Epoch 5 | Train Loss = 0.7854 | Train Acc = 0.7500 | Val Loss = 1.4661 | Val Acc = 0.6250


In [119]:
# Model prediction on eval dataset after training

model.eval()
with torch.no_grad():
    scores = model(eval_dataset.transcripts, eval_dataset.competence_sets)
    acc = torch.sum(torch.argmax(scores, dim=1) == torch.tensor(eval_dataset.label_indices, device=device)).item() / scores.size(0)

print('Predict probabilities:')
print(scores)
print(f'Accuracy: {acc:.2f}')

Predict probabilities:
tensor([[7.6775e-01, 1.1169e-03, 1.1998e-03, 2.2993e-01],
        [2.6204e-01, 8.4582e-03, 2.1771e-01, 5.1180e-01],
        [2.9171e-02, 1.6101e-02, 3.1484e-01, 6.3989e-01],
        [1.7026e-03, 8.1549e-04, 1.1877e-03, 9.9629e-01],
        [9.3343e-01, 6.4669e-02, 8.2373e-04, 1.0730e-03],
        [4.2346e-01, 5.4885e-01, 2.4471e-02, 3.2200e-03],
        [3.0108e-01, 2.6159e-01, 3.7061e-01, 6.6720e-02],
        [3.9420e-02, 8.8789e-01, 5.1850e-02, 2.0839e-02]], device='cuda:0')
Accuracy: 0.62
